# Generated by Django 5.0.3 on 2026-05-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(help_text='操作類型: remove_bg, try_on_2d, try_on_3d', max_length=50)),
                ('status', models.CharField(default='success', help_text='狀態: success, failed', max_length=20)),
                ('bucket', models.CharField(default='history-images', max_length=50)),
                ('object_key', models.CharField(blank=True, help_text='原圖在 MinIO 的路徑', max_length=255, null=True)),
                ('thumb_key', models.CharField(blank=True, help_text='縮圖在 MinIO 的路徑', max_length=255, null=True)),
                ('response_json', models.JSONField(blank=True, help_text='完整的執行結果 JSON', null=True)),
                ('start_ts', models.DateTimeField(help_text='開始時間')),
                ('end_ts', models.DateTimeField(help_text='結束時間')),
                ('exec_time_ms', models.IntegerField(default=0, help_text='總耗時 (毫秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
